services:
  myfinance.api:
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_URLS=http://+:8080
    ports:
      - "8080:8080"
    volumes:
      - ~/.microsoft/usersecrets:/home/app/.microsoft/usersecrets:ro
      - ~/.microsoft/usersecrets:/root/.microsoft/usersecrets:ro