services:
  myfinance.api:
    image: ${DOCKER_REGISTRY-}myfinanceapi
    container_name: MyFinance.Api
    build:
      context: .
      dockerfile: src/API/MyFinance.Api/Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - myfinance.postgres
      - myfinance.redis

  myfinance.postgres:
    image: postgres:latest
    container_name: MyFinance.Postgres
    environment:
      - POSTGRES_DB=myfinance
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
    volumes:
      - ./.containers/db:/var/lib/postgresql
    ports:
      - 5432:5432

  myfinance.redis:
    image: redis:latest
    container_name: MyFinance.Redis
    restart: always
    ports:
      - "6379:6379"
